name: ZIP translation files

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
      tag:
        description: 'Release tag'
        required: true

jobs:
  package-games:
    strategy:
      matrix:
        directory: [duriduri, ae]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install zip utility
      run: sudo apt-get install zip -y

    - name: Create ZIP file from directory
      run: zip -r lang-${{ matrix.directory }}.zip ${{ matrix.directory }}/xml/

    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "lang-${{ matrix.directory }}.zip"
        tag: ${{ github.event.inputs.tag }}
        allowUpdates: true
