name: Compile client
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true


jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Tkinter (Linux)
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install python3-tk
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pywebview
        pip install pyinstaller
    - name: Compile app
      run: |
        pyinstaller -F -w client.py
    - name: Archive build artifacts (Linux)
      if: runner.os == 'Linux'
      run: zip -r ${{ matrix.platform }}-build.zip dist/
    - name: Archive build artifacts (Windows)
      if: runner.os == 'Windows'
      run: powershell Compress-Archive -Path dist\* -DestinationPath ${{ matrix.platform }}-build.zip
    - name: Create release from artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ matrix.platform }}-build.zip"
        tag: ${{ github.event.inputs.tag }}
        allowUpdates: true
